### ISSUE TITLE
Error:  'gnome-terminal' is not recognized as an internal or external command, operable program or batch file

### ISSUE THREAD

**Issue by SwaroopSPradhan** [ICME-India/MicroSim#4]
OS : Windows 10 Version 20H2 (OS Build 19042.985)

After successfully putting the Inputa.in and Fillinga.in for Cahn_Hilliard_FFT_2D and selecting a folder to keep the output.in file, this error pops up when try to Run the code.
![image](https://user-images.githubusercontent.com/92518029/160981772-a71cd233-0f11-4273-a570-1d1ea38389a5.png)

**Comment by AjaySagarR** [comment]
@SwaroopSPradhan,

Thank you so much for reaching out and letting us know. I'm sorry about the issue. Currently, many functionalities are limited in Windows OS. You won't be able to run simulations using MicroSim GUI/script in Windows OS. For the time being, I can recommend you to run the solver manually as instructed in manual.

If you still face any issue, please let me know.
