### ISSUE TITLE
Shows up unknown error while running the KKSOpenCl solver from terminal.

### ISSUE THREAD

**Issue by SwaroopSPradhan** [ICME-India/MicroSim#6]
OS: Ubuntu 20.04.4 LTS
After following all the steps in the given readme with the KKSOpenCl solver some error shows up. Attaching the screenshot below,
![Screenshot from 2022-04-13 17-06-23](https://user-images.githubusercontent.com/92518029/163172229-89f63be8-3ad1-445c-9c55-4853fcee7f85.png)

**Comment by dasarimohan** [comment]
Dear Swaroop, 

Thanks for letting us know the issue. 
In the screenshot attached by you, it shows that "Found 0 platforms!", "No. of platforms 0".  That means OpenCL is not available on the machine.  Depending upon the available hardware on your machine,  the following instructions can help you in resolving the issue

1. For Nvidia GPUs install CUDA toolkit 
2. For AMD GPUs/CPUs install ROCM 
3. For intel CPUs install intel CPU runtime for OpenCL applications 

All the above packages install/require the drivers for CPUs/GPUs from OEMs, so you may need sudo access. 
The OpenCL headers can be installed through "sudo apt-get install  opencl-headers"

**Comment by dasarimohan** [comment]
We'll also add a warning message so that the user is informed if there are no OpenCL platforms available on the machine.
